"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Tim Micheletto"
email = "2153545+tmicheletto@users.noreply.github.com"

[snapshot]
auto-track = "~(.claude/ | CLAUDE.md)"

[aliases]
# see https://github.com/jj-vcs/jj/discussions/2425#discussioncomment-11425112
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]

[git]
# Prevent pushing work in progress or anything explicitly labeled "private"
private-commits = "description(glob:'wip:*') | description(glob:'private:*')"
colocate = true
